### PR TITLE
Support of CryptoNight Waltz based on CryptoNight MoneroV8

### PR DESCRIPTION
**Pull request by EDDragonWolf**

### CODE REVIEW

**Comment by jagerman** [comment]
Can I ask why you decided to tweak CNv2 (aka CN-MoneroV8), rather than CNv0 (the original cryptonight)?  The iteration tweak done here seems almost trivially easy for FPGA bitstream authors to implement: modifying a Monero bitstream to support simply a different number of iterations seems likely to be trivial.

While *any* tweak would get away from NiceHash (the primary goal here), CNv2 iterations have the disadvantage of being a fairly power-hungry algorithm on GPUs compared to the earlier versions (with things like an low-precision integer square root added to deliberately thwart potential ASIC performance).  But also by only being an iteration change rather than any deeper modification, FPGA bitstreams will be so easy to implement (and perhaps even already exist, if the bitstream authors were lucky enough to anticipate different iteration sizes) that we'll likely continue to see GPU miner hashrate being eroded by FPGAs.

On its own that probably doesn't matter that much, but a consequence of this has been that GPU miners have gone elsewhere (predominantly to CN-heavy and variants thereof, it seems).  We currently have less than 1/4 of the network hashrate happening on known pools:

image

**Comment by Patrickdurbin** [comment]
While any specific tweak will make nice hash incompatible.   FPGA would always exists and merge over . So really it doesn't matter which algo you would have used.  Cnv0  etc... 

Fpgas on cvn2   vs heavy.. .. GPU's are not as profitable.. but fpga's don't have such a profit difference. 

It would have been just as simple to change the iteration to this. 

Rx580 8gig will get 1156 hashs    vs 980 hashs on cnv8  on cheap elpida/Hynix memory. Samsung even more.  Its far more efficient. 

https://github.com/graft-project/GraftNetwork/tree/feature/cn-heavy-pow

Although I guess its winter time I can use the extra heat.

**Comment by EDDragonWolf** [comment]
The main goal of this PR, as @jagerman wrote, is a move away from Nicehash, because Hicehash can be used for network centralization and future 51% attacks. We do not think that FPGA bitstreams can be used for it since their cost is larger than GPU cost, but their profit isn't so high at all. FPGA support can be even advantaged for increasing network hashrate if FPGA miners will support network decentralization. However, if you know examples when FPGA was used for large attacks or some large FPGA-based mining pools which support CryptoNight variants, please, provide this information and support us to estimate risks from FPGA.

@jagerman 
> Can I ask why you decided to tweak CNv2 (aka CN-MoneroV8), rather than CNv0 (the original cryptonight)?
Because we already use it. Yes, we can simply move back, but from our current point of view, there isn't a big problem to be based on CNv8. 
Anyway, CNv0 has the largest possibility to be supported by FPGA than any other CryptoNight variants, as well as it has the largest computational power on Nicehash (than other CryptoNight-s), so it potentially means that Nicehash can add support of CNv0 tweaks. 

> On its own that probably doesn't matter that much, but a consequence of this has been that GPU miners have gone elsewhere (predominantly to CN-heavy and variants thereof, it seems). We currently have only 1/4 of the network hashrate happening on known pools:
Yeah, this is a problem, however, I do not think that we get them back only because we switch to heavy or heavy-based tweaks.

@Patrickdurbin
> It would have been just as simple to change the iteration changes to the heavy!
You are right, and Heavy or its tweak is still the option, however, at that moment we don't see the reason to provide FPGA resistance. 
 
> Rx580 8gig will get 1156 hashs vs 980 hashs on cnv8 on cheap elpida/Hynix memory.
I do not think, that direct comparison of hashrate of algorithms makes sense, only if the goal isn't to see larger hashrate.

> Then when monero forks again.
Yes, and potentially we will also apply their changes. Currently, we prepare to merge with Monero and plan to make it periodically (of course, with a smaller period than now :smile:)

**Comment by Patrickdurbin** [comment]
@EDDragonWolf 
Heavy is less profitable on fpgas then cnv2... .
 cnv2 is less profitable on GPU's then Heavy. 

Using heavy brings the cost to mine closer.. meaning gpu's don't get screwed as bad by the FPGA's and the end result is the same. 

If you would have forked the iteration on heavy it would have kept Fpga's on it(because they gonna fork anyway)  and let gpu's be closer profitable.

**Comment by yidakee** [comment]
The closer the hashing power between GPU's and FPGA, the more democratic and decentralized the network becomes. 
 
This alone should motivate the algo changes. 

If GPU are at a clear disadvantage, they will leave the network, and progressively FPGA's will dominate the hashrate. 

GPU are consumer level and available. FPGA highly specialized to source and run, so despite not being NiceHashable, the exact same risk factor in enabled.

**Comment by bitkis** [comment]
Please see a "help wanter" #223

**Comment by SChernykh** [comment]
> cnv2 fpga (widespread 8,000 hash first bitstream)
cnv2 fpga (second generation bitstream 25,000 hash)
cnv2 fpga (private 100,000 hash/s bitstreams) (rumored)

None of these exist. FPGAs (BCU to be specific) can't mine cnv2 faster than 1-2 KH/s. It's not FPGAs that mine cnv2 now, it's ASICs. Stellite and Masari forked more than a week ago with simple iteration change and they're still consistently 2x more profitable than Monero.

**Comment by Patrickdurbin** [comment]
Even if what your saying is true. GPUs would have been brought closer together to the profitability of FPGA using an iteration change of heavy ; as well as, getting off of the Nice Hash support list.  

The further apart in profitability "fpga' sets the minimum profitability on network difficulty" 
The closer together they are in profitability GPU's/fpga's  set the minimum profitability on network difficulty

This is the third fork we have went through because they just fork and never ask questions of what they should do. They keep cloning Monero which is fine... but nicehash always follows monero!!! Monero was never forking to get away from nice hash. They forked to get away from FPGA. 

There are two community solutions for FPGA... (fork away every 6 months) or come up with your own FPGA/GPU algo where they are close together in profitability and just let the fpga's support the network with the increased hash rate. Ryo is doing just that with "CN-GPU" 


For Graft... heavy with a tweak was the quickest solution. instead of cnv2 with a tweak. 

Grafts main problem is they don't take community input as they feel its micromanaging.  Then when we prove to them its the right way. They stop taking input and come up with the solution on their own. If we don't agree with the solution.

The answer is always. "we leave it in the hands of the community if they don't like what we did".

No one would want to do anything for free with that attitude.

**Pull request closed without merging**
